services:

  app:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/webapp
    links:
      - db:db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: webapp
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 20s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  dbdata:
