services:
  
  app:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://app:app@db:3306/app
    links:
      - db:db
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
       test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
       interval: 5s
       timeout: 20s
       retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  dbdata:
