services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_SECRET_KEY: app-secret_key
      WAGTAIL_SITE_NAME: nickmoreton
      WAGTAILADMIN_BASE_URL: http://localhost:8000
      ENVIRONMENT: development
      PYTHONUNBUFFERED: 1

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
