# Generated by Django 4.1.10 on 2023-08-28 14:46

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleChapterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("heading", wagtail.blocks.CharBlock()),
                                        (
                                            "level",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                    ("h6", "H6"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "callout",
                                wagtail.blocks.RichTextBlock(
                                    template="blocks/callout.html"
                                ),
                            ),
                            ("rich_text", wagtail.blocks.RichTextBlock()),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("code", wagtail.blocks.TextBlock()),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("python", "Python"),
                                                    ("html", "HTML"),
                                                    ("css", "CSS"),
                                                    ("javascript", "JavaScript"),
                                                    ("bash", "Bash"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_aligned_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                ("excerpt", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("heading", wagtail.blocks.CharBlock()),
                                        (
                                            "level",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                    ("h6", "H6"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "callout",
                                wagtail.blocks.RichTextBlock(
                                    template="blocks/callout.html"
                                ),
                            ),
                            ("rich_text", wagtail.blocks.RichTextBlock()),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("code", wagtail.blocks.TextBlock()),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("python", "Python"),
                                                    ("html", "HTML"),
                                                    ("css", "CSS"),
                                                    ("javascript", "JavaScript"),
                                                    ("bash", "Bash"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_aligned_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("heading", wagtail.blocks.CharBlock()),
                                        (
                                            "level",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                    ("h6", "H6"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "callout",
                                wagtail.blocks.RichTextBlock(
                                    template="blocks/callout.html"
                                ),
                            ),
                            ("rich_text", wagtail.blocks.RichTextBlock()),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("code", wagtail.blocks.TextBlock()),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("python", "Python"),
                                                    ("html", "HTML"),
                                                    ("css", "CSS"),
                                                    ("javascript", "JavaScript"),
                                                    ("bash", "Bash"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_aligned_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                ("excerpt", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(verbose_name="Article published date")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PackageIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("heading", wagtail.blocks.CharBlock()),
                                        (
                                            "level",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                    ("h6", "H6"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "callout",
                                wagtail.blocks.RichTextBlock(
                                    template="blocks/callout.html"
                                ),
                            ),
                            ("rich_text", wagtail.blocks.RichTextBlock()),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("code", wagtail.blocks.TextBlock()),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("python", "Python"),
                                                    ("html", "HTML"),
                                                    ("css", "CSS"),
                                                    ("javascript", "JavaScript"),
                                                    ("bash", "Bash"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_aligned_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PackagePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("heading", wagtail.blocks.CharBlock()),
                                        (
                                            "level",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("h1", "H1"),
                                                    ("h2", "H2"),
                                                    ("h3", "H3"),
                                                    ("h4", "H4"),
                                                    ("h5", "H5"),
                                                    ("h6", "H6"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "callout",
                                wagtail.blocks.RichTextBlock(
                                    template="blocks/callout.html"
                                ),
                            ),
                            ("rich_text", wagtail.blocks.RichTextBlock()),
                            (
                                "code",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("code", wagtail.blocks.TextBlock()),
                                        (
                                            "language",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("python", "Python"),
                                                    ("html", "HTML"),
                                                    ("css", "CSS"),
                                                    ("javascript", "JavaScript"),
                                                    ("bash", "Bash"),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "image_aligned_block",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ]
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                ("date", models.DateField(verbose_name="Package published date")),
                ("excerpt", models.CharField(blank=True, max_length=255)),
                ("pypi_package_name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
