# Generated by Django 4.1.10 on 2023-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_remove_articlechapterpage_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagepage",
            name="pypi_package_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
